import React from 'react';
import Footer from '../../Components/Footer';

const s2002 = () => {
    return (
        <div>
            <div className="container">
                <h3 className="article-head center">Adani Group’s Solar Project</h3>
                <div className="center article-content" style={{ textAlign: "center" }}>
                    Market Research by <b><a href="http://linkedin.com/in/sarang-sanil-b501211b0">Sarang Sanil</a></b> <br />
                </div>
                <p className="article-subhead">About the company</p>
                <p className="article-content">In the year 1988, Gautam Shantilal Adani started to build an empire. But little did this emperor
                know that in the next 32 years he was going to create a realm having a market cap of $22 billion,
                the Adani Group. An Indian multinational conglomerate, Adani Group, headquartered in
                Ahmedabad, Gujarat has 6 publicly traded companies under it. Gautam Adani founded the Adani
                group for commodity trading business. From this business, Adani Group grew on to diversify
                into various fields operating at 70 locations in 50 countries. This Indian MNC has its operations
                in trading, coal mining, energy supply, port development etc. This group has set various
                benchmarks not only for Indian companies but multinational conglomerates across the world.
                From operating India’s largest private port in 2002 to becoming India’s largest private power
                producer in 2014 to winning the world’s largest solar energy tender in 2020, the Adani group has
                expanded tremendously. This successful conglomerate has shown substantial growth throughout
                    its existence both domestically and internationally.</p>
                <p className="article-subhead">The building of an empire</p>
                <p className="article-content">In 1988, Gautam Adani started a firm that imports polyvinyl chloride (PVC), which is an essential material for the manufacturing of plastic. When the Government of India announced the Liberalisation, Privatisation and Globalisation (LPG) of the Indian economy, Mr Adani capitalised on this opportunity and expanded his business. In 1995, the Adani Group won the contract for privately operating the Mundra Port in Gujarat which later went on to become the largest private commercial port in India. Having the privilege of access to the port, this corporation also became the most significant net foreign exchange earner of the country. In the year 1996, Adani Group established Adani Power limited for development and maintenance of power projects in India. This company has a combined installed capacity of 10,440 MW with four thermal power projects across India which paved them the opportunity of becoming the country’s largest private energy producer by 2014. Through incorporation with a Singapore-based Wilmar International in 1999, Adani-Wilmar joint venture gave rise to the country’s largest edible oil production under the brand name Fortune. Coal has played an essential role in the group’s success. In 1999 Adani group ventured into the coal management under the company name, Adani Enterprises Ltd.(AEL). The company became the first private miner of India and in 2006 won the first Mine Developer and Operator (MDO) contract. But Adani Enterprises did not just settle for the domestic game but also expanded internationally to Indonesia and Australia. Had the company implemented the Carmichael coal mine (Australia) project, it would have become the world’s largest coal mine. Nevertheless, Adani Enterprises Ltd. became India’s largest coal mining company in 2010. The Adani group, in late December, founded Adani Transmission Ltd. (ATL), a company set up for operating and maintaining electric power transmission systems. This company went on to get listed on the only two stock exchanges in India in the year 2015 and by 2020 ATL became the country’s biggest private power transmission company with a mind-boggling market share of 25%.  In the year 2005, this Indian MNC established yet another successful company under its name, Adani Gas Limited (AGL). This company develops City Gas Distribution (CGD) networks to supply the  Piped Natural Gas (PNG) to the Industrial, Commercial, Domestic (residential) and Compressed Natural Gas (CNG) to the transport sector. AGL got listed in both the stock exchanges (NSE, BSE) in the year 2018 and has already become India’s largest city gas distribution company. Adani group has shown tremendous success in all the fields it operates. But Gautam Adani had also built something for the future. Something the world will need for self-sustenance. The Adani group made a company eyeing on a global scale, and that is the Adani Green Energy Limited.   </p>
                <p className="article-subhead">Adani Green Energy Limited (AGEL)</p>
                <p className="article-content">Adani Green Energy Limited, founded in the year 2015, is one of the futuristic companies of the Adani group. This company aims at providing a better, cleaner and greener future for the world. AGEL is a company that develops, builds, owns, operates and maintains solar and wind farm projects. Their projects are primarily based in India but with the vision of providing renewable energy to the world. The electricity generated by the company is supplied to central and state government entities and also to those corporations that are backed by the government. AGEL has long-term Power Purchase Agreements (PPAs) that were made with the central and the state governments which give the company the rights to supply to the government entities for 25 years and so far the company has extended to 66 locations and 11 states in India. The portfolio of the company includes 54 currently operational projects along with the company’s asset base of $2 billion. Adding to their collection is the production of 13,990 MW of renewable energy and the saving of 2 million tonnes equivalent of CO2. The company also has a solar power plant set up in Kamuthi, which spreads across 2500 acres of land and produces 648 MW, making it the largest single location power plant. Though the company has extended its service to solar and wind power, it was established to provide hybrid power also in the future. Having the vision of delivering 25GW of electricity by 2025, the company achieved a historic feat in early 2020. Adani Green Energy Limited won the world’s largest solar contract worth $6 billion. This project aims at delivering 8 GW of solar power. Under this contract, the company has also committed to establishing  2 GW of additional solar cell and module manufacturing capacity which in turn increases the company’s portfolio capacity to an astronomical 15 GW of renewable energy under operation, construction or any contract. The deliverance of the 8 GW will be implemented by 2025, and this will help AGEL to become the world’s largest renewables company. The project is also expected to create 4 lakh direct and indirect jobs. </p>
                <p className="article-subhead">Future of renewable energy</p>
                <p className="article-content">Even with an infinite supply of renewable energy, the world has not exploited this potential source as much as it did concerning non-renewable energy. The prime reasons for this are the high cost of installation, slow technological advancements etc. In 2020 only 26% of the world’s electricity is delivered by renewable energy sources. By 2024, it is predicted that renewable electricity will grow by 1200GW. Solar power will become cheaper to produce, which will, in turn, make the coal-based power unprofitable. This shift will not only help in generating more affordable electricity but also reduces the carbon emission, thus improving the environmental conditions.</p>
                <p className="article-content">With 1.3 billion people, India is the world’s fourth-largest carbon emitter. Majorly contributing to this is the power sector which uses fossil fuels to meet 82% of its demand. It is high time to change the energy mix in India and bring in more innovative and less expensive techniques to harvest the non-fossil sources. India aims to attain 175GW of renewable energy by 2020, which will include 100GW from solar energy, 60GW from wind power, 10GW from bio-power and the rest 5GW from hydropower plants. India has already committed to producing 40% of its requirement using renewable energy sources by 2030. With renewable sources showing such incredible prospects for growth, the Adani group can take advantage of this potentiality and help India build a more environmentally friendly economy. </p>
                <div className="references">
                    <p className="article-subhead">
                        References
                     </p>
                    <ol className="article-content">
                        <li><a href="https://www.adani.com/About-us">https://www.adani.com/About-us</a></li>
                        <li><a href="https://en.wikipedia.org/wiki/Adani_Group">https://en.wikipedia.org/wiki/Adani_Group</a></li>
                        <li><a href="https://indianexpress.com/article/business/companies/adani-green-energy-rs-45000-crore-solar-project-seci-6450209/">https://indianexpress.com/article/business/companies/adani-green-energy-rs-45000-crore-solar-project-seci-6450209/</a></li>
                        <li><a href="https://www.storypick.com/gautam-adani-story/">https://www.storypick.com/gautam-adani-story/</a></li>
                        <li><a href="https://www.adaniwilmar.com/about-us">https://www.adaniwilmar.com/about-us</a></li>
                        <li><a href="https://www.adanienterprises.com/businesses/integrated-coal-management">https://www.adanienterprises.com/businesses/integrated-coal-management</a></li>
                        <li><a href="https://www.business-standard.com/company/adani-transmissi-66273/information/company-history">https://www.business-standard.com/company/adani-transmissi-66273/information/company-history</a></li>
                        <li><a href="https://www.bloombergquint.com/markets/why-adani-transmission-is-the-best-performer-in-power-index">https://www.bloombergquint.com/markets/why-adani-transmission-is-the-best-performer-in-power-index</a></li>
                        <li><a href="https://www.business-standard.com/company/adani-gas-39108/information/company-history">https://www.business-standard.com/company/adani-gas-39108/information/company-history</a></li>
                        <li><a href="https://www.thehindu.com/business/Industry/adani-green-energy-ltd-bags-worlds-largest-solar-contract-worth-6-billion/article31784926.ece">https://www.thehindu.com/business/Industry/adani-green-energy-ltd-bags-worlds-largest-solar-contract-worth-6-billion/article31784926.ece</a></li>
                        <li><a href="https://earth.org/the-growth-of-renewable-energy-what-does-the-future-hold/#:~:text=Renewable%20energy%20sources%20make%20up,to%20reach%2030%25%20by%202024.&text=Overall%2C%20renewable%20electricity%20is%20predicted,electricity%20capacity%20of%20the%20US. ">https://earth.org/the-growth-of-renewable-energy-what-does-the-future-hold/#:~:text=Renewable%20energy%20sources%20make%20up,to%20reach%2030%25%20by%202024.&text=Overall%2C%20renewable%20electricity%20is%20predicted,electricity%20capacity%20of%20the%20US. </a></li>
                        <li><a href="https://energy.economictimes.indiatimes.com/energy-speak/the-future-of-renewable-energy-in-india/3016">https://energy.economictimes.indiatimes.com/energy-speak/the-future-of-renewable-energy-in-india/3016</a></li>
                    </ol>
                </div>

            </div>
            <Footer />
        </div>
    )
}

export default s2002;
