export const GET_COMMUNITY_POSTS = 'GET_COMMUNITY_POSTS';
export const GET_COMMUNITY_POSTS_LOADING = 'GET_COMMUNITY_POSTS_LOADING';
export const GET_COMMUNITY_POSTS_FAILED = 'GET_COMMUNITY_POSTS_FAILED';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_LOADING = 'GET_PRODUCTS_LOADING';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const GET_TODAY_LAUNCH = 'GET_TODAY_LAUNCH';
export const GET_TODAY_LAUNCH_LOADING = 'GET_TODAY_LAUNCH_LOADING';
export const GET_TODAY_LAUNCH_FAILED = 'GET_TODAY_LAUNCH_FAILED';

export const GET_TRENDING_PRODUCTS = 'GET_TRENDING_PRODUCTS';
export const GET_TRENDING_PRODUCTS_LOADING = 'GET_TRENDING_PRODUCTS_LOADING';
export const GET_TRENDING_PRODUCTS_FAILED = 'GET_TRENDING_PRODUCTS_FAILED';

export const GET_JOB_PROFILES = 'GET_JOB_PROFILES';
export const GET_JOB_PROFILES_LOADING = 'GET_JOB_PROFILES_LOADING';
export const GET_JOB_PROFILES_FAILED = 'GET_JOB_PROFILES_FAILED';

export const GET_JOBS = 'GET_JOBS';
export const GET_JOBS_LOADING = 'GET_JOBS_LOADING';
export const GET_JOBS_FAILED = 'GET_JOBS_FAILED';

export const GET_INTERNSHIPS = 'GET_INTERNSHIPS';
export const GET_INTERNSHIPS_LOADING = 'GET_INTERNSHIPS_LOADING';
export const GET_INTERNSHIPS_FAILED = 'GET_INTERNSHIPS_FAILED';

export const GET_USER_DETAILS = 'GET_USER_DETAILS';
export const GET_USER_DETAILS_LOADING = 'GET_USER_DETAILS_LOADING';
export const GET_USER_DETAILS_FAILED = 'GET_USER_DETAILS_FAILED';
